apiVersion: v1
kind: PersistentVolume
metadata:
  name: backend-pv
  namespace: production
spec:
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteMany 
  persistentVolumeReclaimPolicy: Retain
  # แก้ไข: ลบ hostPath แล้วใช้ NFS แทน
  nfs: 
    path: /mnt/k8s_backend_uploads # Path Export บน NFS Server
    server: 10.10.10.9       # IP ของ NFS Server
