apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: foodstore
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: filmfilm/foodstore-backend:latest  # ← ดึงจาก Docker Hub โดยตรง
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://mysql:3306/shopdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_USER
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWORD
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: "update"
        volumeMounts:
        - name: uploads
          mountPath: /app/uploads/images
      volumes:
      - name: uploads
        emptyDir: {}  # ใช้ PersistentVolume ใน production
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: foodstore
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: backend
