apiVersion: v1
kind: PersistentVolume
metadata:
  name: backend-pv
  namespace: production
spec:
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/backend  # path บน node ของคุณ
  persistentVolumeReclaimPolicy: Retain
