apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: filmfilm/foodstore-backend:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://$(DB_HOST_NAME):3306/shopdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_USER
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWORD
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: "update"
        volumeMounts:
        - name: uploads
          mountPath: /app/uploads/images
      volumes:
      - name: uploads
        persistentVolumeClaim:
          claimName: backend-pvc   # ใช้ PVC ที่สร้างไว้
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: production
spec:
  type: NodePort   # เปิด NodePort เพื่อเข้าจาก IP ภายนอก
  selector:
    app: backend
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000  # เลือก port ระหว่าง 30000-32767 หรือไม่กำหนดให้ k8s auto
