apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-admin
  namespace: foodstore
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend-admin
  template:
    metadata:
      labels:
        app: frontend-admin
    spec:
      containers:
      - name: frontend
        image: filmfilm/foodstore-admin-frontend:latest
        ports:
        - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-admin
  namespace: foodstore
spec:
  ports:
  - port: 3001
    targetPort: 3001
  selector:
    app: frontend-admin
