apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-admin
  namespace: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend-admin
  template:
    metadata:
      labels:
        app: frontend-admin
    spec:
      containers:
      - name: frontend
        image: filmfilm/foodstore-admin-frontend:latest
        ports:
        - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-admin
  namespace: production
spec:
  type: NodePort               # เปลี่ยนเป็น NodePort
  selector:
    app: frontend-admin
  ports:
    - port: 3001               # service port
      targetPort: 3001         # containerPort ของ pod
      nodePort: 31001          # port ที่เปิดบน Node (สามารถเลือก 30000-32767)
