apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-admin
  namespace: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend-admin
  template:
    metadata:
      labels:
        app: frontend-admin
    spec:
      containers:
      - name: frontend-admin
        image: filmfilm/foodstore-admin-frontend:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-admin
  namespace: production
spec:
  type: NodePort
  selector:
    app: frontend-admin
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31001
