apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-user
  namespace: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend-user
  template:
    metadata:
      labels:
        app: frontend-user
    spec:
      containers:
      - name: frontend
        image: filmfilm/foodstore-user-frontend:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-user
  namespace: production
spec:
  type: NodePort               # เปลี่ยนเป็น NodePort
  selector:
    app: frontend-user
  ports:
    - port: 3000               # service port
      targetPort: 3000         # containerPort ของ pod
      nodePort: 31000          # port ที่เปิดบน Node
