apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-salaya
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-salaya
  template:
    metadata:
      labels:
        app: mysql-salaya
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_ROOT_PASSWORD
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
        - name: mysql-config
          mountPath: /etc/mysql/conf.d
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
      - name: mysql-config
        configMap:
          name: mysql-config-slave
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-salaya
  namespace: production
spec:
  selector:
    app: mysql-salaya
  ports:
    - port: 3306
      targetPort: 3306
  type: ClusterIP
