apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-master
  namespace: production
data:
  mysql-init.sql: |
    CREATE USER 'repl'@'%' IDENTIFIED BY 'replpassword';
    GRANT REPLICATION SLAVE ON *.* TO 'repl'@'%';
    FLUSH PRIVILEGES;
