apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-salaya
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-salaya
  template:
    metadata:
      labels:
        app: mysql-salaya
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: MYSQL_DATABASE
              key: MYSQL_DATABASE
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: MYSQL_USER
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: MYSQL_PASSWORD
              key: MYSQL_PASSWORD
        - name: MYSQL_SERVER_ID
          value: "2"
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
        - name: init-sql
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
      - name: init-sql
        configMap:
          name: mysql-init-slave
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-salaya
  namespace: production
spec:
  selector:
    app: mysql-salaya
  ports:
    - port: 3306
      targetPort: 3306
  type: ClusterIP
