apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config-slave
  namespace: production
data:
  my.cnf: |
    [mysqld]
    server-id=2
    log_bin=mysql-bin
    gtid_mode=ON
    enforce_gtid_consistency=ON
    binlog_format=ROW
