apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: production
spec:
  accessModes:
    - ReadWriteOnce   # pod เดียวเขียนอ่านได้
  resources:
    requests:
      storage: 15Gi     # กำหนดขนาดพื้นที่
