apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: production
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3N3b3Jk  # base64 of "rootpassword"
  MYSQL_DATABASE: c2hvcGRi               # base64 of "shopdb"
  MYSQL_USER: c2hvcHVzZXI=                # base64 of "shopuser"
  MYSQL_PASSWORD: c2hvcHBhc3N3b3Jk       # base64 of "shoppassword"
