export const recentOrders = [
  {
    avatar: "https://randomuser.me/api/portraits/men/32.jpg",
    date: "Dec 30, 2019 07:52",
    price: "$8.99",
    status: "Pending",
    statusColor: "red",
    productImg: "https://png.pngtree.com/png-clipart/20250517/original/pngtree-watermelon-png-image_21022151.png",
  },
  {
    avatar: "https://randomuser.me/api/portraits/women/44.jpg",
    date: "Dec 30, 2019 05:18",
    price: "$6.48",
    status: "Pending",
    statusColor: "red",
    productImg: "https://png.pngtree.com/png-vector/20250206/ourlarge/pngtree-a-plate-of-french-fries-with-white-sauce-on-it-png-image_15394414.png",
  },
  {
    avatar: "https://randomuser.me/api/portraits/men/23.jpg",
    date: "Dec 4, 2019 21:42",
    price: "$17.84",
    status: "Complete",
    statusColor: "green",
    productImg: "https://png.pngtree.com/png-clipart/20250115/original/pngtree-bread-with-cream-cheese-and-basil-png-image_19799068.png",
  },
  {
    avatar: "https://randomuser.me/api/portraits/men/50.jpg",
    date: "Mar 20, 2019 23:14",
    price: "$6.48",
    status: "Pending",
    statusColor: "red",
    productImg: "https://png.pngtree.com/png-vector/20231016/ourmid/pngtree-burger-food-png-free-download-png-image_10199386.png",
  },
  {
    avatar: "https://randomuser.me/api/portraits/women/60.jpg",
    date: "Dec 7, 2019 23:26",
    price: "$14.81",
    status: "Pending",
    statusColor: "red",
    productImg: "https://png.pngtree.com/png-clipart/20201212/ourmid/pngtree-lettuce-vegetables-png-image_2543323.jpg",
  },
  {
    avatar: "https://randomuser.me/api/portraits/men/65.jpg",
    date: "Feb 2, 2019 19:28",
    price: "$14.81",
    status: "Complete",
    statusColor: "green",
    productImg: "https://img.lovepik.com/free-png/20211126/lovepik-cola-png-image_401163531_wh1200.png",
  },
  {
    avatar: "https://randomuser.me/api/portraits/men/65.jpg",
    date: "Feb 2, 2019 19:28",
    price: "$5.22",
    status: "Complete",
    statusColor: "green",
    productImg: "https://png.pngtree.com/png-vector/20240630/ourlarge/pngtree-delicious-extra-cheezy-burger-food-and-clipart-png-image_12891905.png",
  },
  {
    avatar: "https://randomuser.me/api/portraits/men/65.jpg",
    date: "Feb 2, 2019 19:28",
    price: "$5.22",
    status: "Pending",
    statusColor: "red",
    productImg: "https://e7.pngegg.com/pngimages/649/388/png-clipart-lemon-juice-illustration-orange-juice-lemonade-lemon-juice-lemon-food-citrus-thumbnail.png",
  },
  {
    avatar: "https://randomuser.me/api/portraits/men/22.jpg",
    date: "Dec 4, 2019 21:42",
    price: "$5.22",
    status: "Complete",
    statusColor: "green",
    productImg: "https://png.pngtree.com/png-vector/20250206/ourlarge/pngtree-a-plate-of-french-fries-with-white-sauce-on-it-png-image_15394414.png",
  },
  {
    avatar: "https://randomuser.me/api/portraits/women/32.jpg",
    date: "Dec 30, 2019 07:52",
    price: "$14.81",
    status: "Pending",
    statusColor: "red",
    productImg: "https://png.pngtree.com/png-vector/20231016/ourmid/pngtree-burger-food-png-free-download-png-image_10199386.png",
  },
  {
    avatar: "https://randomuser.me/api/portraits/men/49.jpg",
    date: "Dec 7, 2019 23:26",
    price: "$6.48",
    status: "Complete",
    statusColor: "green",
    productImg: "https://e7.pngegg.com/pngimages/649/388/png-clipart-lemon-juice-illustration-orange-juice-lemonade-lemon-juice-lemon-food-citrus-thumbnail.png",
  },
  {
    avatar: "https://randomuser.me/api/portraits/men/88.jpg",
    date: "Mar 20, 2019 23:14",
    price: "$8.99",
    status: "Pending",
    statusColor: "red",
    productImg: "https://img.lovepik.com/free-png/20211126/lovepik-cola-png-image_401163531_wh1200.png",
  },
];

export const topProducts = [
  "Kerala Chicken Roast",
  "Spicy BBQ Jackfruit Tacos",
  "Kochchi Prawn Spaghetti",
];

export const inventoryAlerts = [
  { name: "Kerala Chicken Roast", value: 3 },
  { name: "Spicy BBQ Jackfruit Tacos", value: 2 },
  { name: "Kochchi Prawn Spaghetti", value: 4 },
];