{
 "title": "Spring Boot Logs (Loki)",
 "tags": [
  "loki",
  "spring",
  "logs"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Recent Application Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"docker\"} |~ \"request-logger\"\n| pattern \"<_> : <body>\"\n| json body\n| line_format \"{{.body.client_ip}} {\\\"method\\\":\\\"{{.body.method}}\\\",\\\"uri\\\":\\\"{{.body.uri}}\\\",\\\"status\\\":{{.body.status}},\\\"duration_ms\\\":{{.body.duration_ms}}}\""
    }
   ]
  },
  {
   "title": "Error Logs (Loki)",
   "type": "logs",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{job=\"docker\"} |= \"ERROR\""
    }
   ]
  },
  {
   "title": "Request Logs by Endpoint",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "{job=\"docker\"} |~ \"request-logger\"\n| pattern \"<_> : <body>\"\n| json body\n| label_format method=\"{{.body.method}}\", uri=\"{{.body.uri}}\", status=\"{{.body.status}}\", duration_ms=\"{{.body.duration_ms}}\""
    }
   ]
  },
  {
   "title": "Log Volume Over Time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 6, "y": 21 },
   "targets": [
    {
     "expr": "count_over_time({job=\"docker\"} |~ \"request-logger\" [1m])"
    }
   ]
  },
  {
   "title": "Error Volume Over Time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 21 },
   "targets": [
    {
     "expr": "count_over_time({job=\"docker\"} |= \"ERROR\" [1m])"
    }
   ]
  },
  {
   "title": "Log Heatmap (Traffic Density)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "count_over_time({job=\"docker\"} |~ \"request-logger\" [10s])"
    }
   ]
  },
  {
   "title": "Requests Per Second by Endpoint (Prometheus)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (uri) (rate(http_server_requests_seconds_count{job=\"api_metrics\",outcome!=\"REDIRECTION\"}[1m]))",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "4xx and 5xx Errors (Prometheus)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=\"api_metrics\",status=~\"4..\"}[1m]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=\"api_metrics\",status=~\"5..\"}[1m]))",
     "legendFormat": "5xx"
    }
   ]
  }
 ]
}